server:
  port: 8081
spring:
  application:
    name: hospital-service
  data:
    mongodb:
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
      database: ${MONGO_DATABASE:hospital-db}
      repositories:
        enabled: 'true'
  sql:
    init:
      mode: always
  # swagger-ui custom path
  springdoc:
    swagger-ui: path=/swagger-ui.html

  http:
    multipart:
    # Max file size.
    max-file-size: 1Mb
    # Max request size.
    max-request-size: 10Mb
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
